name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 
        
      - name: Sync files to S3 bucket
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --follow-symlinks
        env:
          AWS_S3_BUCKET: aws-fundamentals-task-tamar-abramishvili
          AWS_REGION: us-east-1  
          SOURCE_DIR: './'  
          DEST_DIR: '/'
