# name: Upload Website

# on:
#   push:
#     branches:
#     - main

# jobs:
#   deploy-site:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --delete
#         env:
#           AWS_S3_BUCKET: YOUR BUCKET NAME
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           SOURCE_DIR: ./main


name: Deploy Static Website to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1  
        
      - name: Sync files to S3 bucket
        run: |
          aws s3 sync ./ s3://aws-fundamentals-task-tamar-abramishvili/ \
            --delete \
            --cache-control "max-age=31536000" \
            --acl public-read
